baseurl = "/"
title = "A.Hecksher"

theme = "hugo-coder"

languagecode = "en"

paginate = 20
canonifyurls = true
googleAnalytics = "UA-127725779-1"
pygmentsstyle = "b2"
pygmentscodefences = true
pygmentscodefencesguesssyntax = true
enableEmoji = true

ignoreFiles = ["\\.Rmd$", "_files$", "_cache$"]

#disqusShortname = "yourdiscussshortname"

[params]
    author = "Aarron Hecksher"
    description = "Aarron Hecksher's personal website"
    keywords = "blog,data science,developer,personal"
    info = "Data Scientist - Technologist - Problem Solver"
    avatarurl = "images/ahecksher.jpg"
    footercontent = "Look what you made me do."

    dateformat = "January 2, 2006"

    hideCredits = false
    hideCopyright = false

    # Git Commit in Footer, uncomment the line below to enable it.
    #commit = "https://github.com/luizdepra/hugo-coder/tree/"

    rtl = false

    # Custom CSS
    custom_css = []

[[params.social]]
    name = "Github"
    icon = "fab fa-github"
    weight = 1
    url = "https://github.com/ahecksher/"
[[params.social]]
    name = "Twitter"
    icon = "fab fa-twitter"
    weight = 3
    url = "https://twitter.com/aahecksher/"
[[params.social]]
    name = "LinkedIn"
    icon = "fab fa-linkedin"
    weight = 4
    url = "https://www.linkedin.com/in/aarronhecksher/"


[[menu.main]]
    name = "BLOG"
    weight = 1
    url  = "/post/"
[[menu.main]]
    name = "ABOUT"
    weight = 2
    url = "/about/"
[[menu.main]]
    name = "RESUME"
    weight = 3
    url = "/resume/"



