---
title: "Who Am I?"
author: "Aarron Hecksher"
date: "August 10, 2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

My name is Aarron Hecksher and I'm a data scientist.  I absolutely love using the R language and exploring the multitude of things you can do (the R community is really amazing!) but Python is starting to grow on me and I'm not real sure how I feel about that ;).  I enjoy learning about and creating solutions using machine learning, bayesian data analysis, natural language processing, and time-series analysis.  All views and opinions are my own.

I graduated from the University of Arkansas with a Bachelors of Science in Industrial Engineering (and the obligatory minor in Mathematics).  I was drawn to industrial engineering because the idea of solving complex problems through the thoughtful design, careful observation, and statiscal analysis sounded like a fun way to make a living.  I've taken and grown that skillset across industries ranging from aerospace/manufacturing at [Spirit Aerosystems](https://www.spiritaero.com) to finance/auditing at [Connolly](https://www.cotiviti.com/connoly) to my current role in retail/cpg analytics, where I was a founding member for [Atlas Technology Group](https://www.atlasdsr.com) and currently enjoy a role as a data architect at [Unilever](https://www.unilever.com).

In my free time you can catch me playing with my daughters, enjoying date nights with my wife, or find me eye balls deep in a syfy/data science/stats book or MOOC.

This blog was built using the incredibly useful [blogdown package](https://github.com/rstudio/blogdown), [Hugo](https://gohugo.io), and [Netlify](https://www.netlify.com).