---
author: Aarron Hecksher
date: '2018-10-19'
slug: resume
categories: []
tags: []
---

### Objective
I help my clients solve problems big and small using data science mixed with an insatiable curiosity and a dash of creativity.

Primary domain expertise in the CPG/Retail Industry with multiple retailers (Walmart, Target, Kroger, etc.) for both Brick and Mortar stores as well as E-Commerce. 

Specific interests in machine learning, bayesian data analysis, natural language processing, and time-series analysis.

### Education
* UNIVERSITY OF ARKANSAS | 2005 | BS in Industrial Engineering (Mathematics minor)

### Skills & Abilities
* Personal: Communication, Project Management, Cross-functional Team Leadership, Management, Customer Service
* Programming: C#, SQL, R, Python 3, VBA, PowerShell, T-SQL, Shiny, GIT
* DBMS: MS SQL Server, Vertica, Postgres, MS Access
* Application Specific: MS Office suite, RStudio, Rodeo, MS Machine Learning Server, Shiny

### Interests & Hobbies
* Perpetually and purposefully learning.
* Reading or listening to thought provoking science fiction.
* Spending time with my wife and 3 daughters.
* Always dreaming of the next big thing.

### Experience
##### PRINCIPAL DATA SCIENTIST | One Stone | 12/2018 - Current
* Doing data science things with my data science friends!

##### DIRECTOR OF SPECIAL PROJECTS | ATLAS TECHNOLOGIES | 3/2014 – 12/2018
* Tasked with solving non-traditional business problems across multiple teams internally and multiple clients externally.
* Co-Architect and maintainer of ATLAS’s OSA (On Shelf Availability) product. Created to help scientifically identify troublesome items to give additional visibility in reporting and maximize a retail operations team’s time in store. Infinitely configurable.
* Creator of the “Closed Loop Reporting” process for Retail Operations clients that helps more accurately identify the efficiency, effectiveness, and ROI of retail operations teams.
* Development of data science specific metrics and processes for Canopy (e-commerce reporting platform) including mining of review topics, sentiment analysis, sales forecasting, and online listing analysis. 

##### FOUNDING MEMBER & BI/OPERATIONS MANAGER | ATLAS TECHNOLOGIES | 6/2012 – 3/2014
* As part of the founding team, I helped grow ATLAS from a team of 5 to 70+, supporting over 600 different vendors, many of which are the in the top 100  CPG companies worldwide.
Duties included:
* Client Management
* Subject Matter Expert on Retail Link data and metrics (WALMART).
* Creation of client specific reporting using the ATLAS platform and other custom solutions to help ensure our client's analytical success with ATLAS
* Management, training, and growth of our Business Intelligence Team

##### BUSINESS SYSTEMS ANALYST - WALMART | CONNOLLY, INC. | 6/2011 – 6/2012
* Served as part of the developer team in support of the accounts payable auditing team for WALMART INC. by developing specialized tools and processes specific to WALMART financial data and email communication that enabled the team to recover more than $80M for the year.  This included: 
    + SQL Server based processes for discovering anomalies and inconsistencies in financial data to write claims on. 
    + PowerShell scripts for processing emails, including attachments, and then storing it in standardized tables where the data could then be used by other processes find discrepancies based on contractual agreements with vendors.
    
##### BUSINESS SYSTEMS ANALYST – SHARED SERVICES | CONNOLLY, INC. | 9/2009 – 6/2011
* Sole developer that engineered and created new systems and business processes for the newly created shared services division that enabled a small (< 10) team to recover $20M+ yearly in invoice statement credits and unclaimed property for commercial and retail clients.  This included:
    + Statement Tracker – MS Access / SQL Server based workflow solution that allowed team members to log and track items and contacts.
    + Client Communicator – MS Access based solution that allowed for mass emailing, faxing, and tracking of organizations that owed clients.

##### INDUSTRIAL ENGINEER | SPIRIT AEROSYSTEMS | 6/2005 – 9/2009
* Developed small scale software solutions using MS Access / SQL Server based on industrial engineering principles.  This included:
    + Advanced Tracking System – reporting system that integrated multiple data sources to give company wide visibility during the start up phase of the 787 program.
    + Advanced Planning Tools – reporting and notification system for 787 program that integrated data from Design Engineering systems (CATIA/ENOVIA) and Manufacturing Engineering (HMS) to quickly identify and help resolve discrepancies.
    + Electronic Rejection Tag System – MS Access / SQL Server based solution to track and automate the work flow of rejection tags during manufacturing.  Reduced downtime from 6 hours to 15 minutes.
